name: CI and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update

      - name: Start mock server
        run: |
          nohup node test/mock_server.js &

      - name: Run Bats tests
        run: |
          bats test/

      - name: Minify bash scripts
        run: |
          npx bash-minifier ./bin/git-jira-fast-ticket.sh > ./bin/git-jira-fast-ticket.min.sh

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
